# Generated by Django 5.0.6 on 2024-07-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dammi',
        ),
    ]
