import { Exercise } from "../types";
import ShoulderImg from '../assets/images/shoulder.jpg';
import ElbowImg from '../assets/images/elbow.jpg';
import AnkleImg from '../assets/images/ankle.png';
import HipImg from '../assets/images/hip.jpg';
import KneeImg from '../assets/images/knee.jpg';
import WristImg from '../assets/images/wrist.jpg';
import HandsImg from '../assets/images/toe.png';
import ToeImg from '../assets/images/hands.jpg';
export const exercises:Exercise[]=[
    {
        exerciseName:'Shoulder',
        image:ShoulderImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Elbow',
        image:ElbowImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Ankle',
        image:AnkleImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Hip',
        image:HipImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Knee',
        image:KneeImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Wrist',
        image:WristImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Hands',
        image:HandsImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
    {
        exerciseName:'Toes',
        image:ToeImg,
        positions:[
            {
                positionImg:'',
                positionName:'Standing'
            },
            {
                positionImg:'',
                positionName:'Sitting'
            },
            {
                positionImg:'',
                positionName:'Lying'
            }
        ]
    },
]